title: Matthew spina
tagline: 'Security Analyst | Penetration Tester | Bug bounty hunter | Freelancer'
description: 'A minimal, portfolio, sidebar, bootstrap Jekyll theme with responsive web design and focuses on text presentation.'
url: 'https://matthew-spina.github.io/'
author: 'Matthew Spina'
avatar: /assets/img/sample/avatar.jpg
github:
    username: Matthew-Spina
twitter:
    username: 'Matthew spina'
social:
    name: 'Matthew Spina'
    email: Matthew_Spina@protonmail.com
    links:
        - 'https://twitter.com/Matthewspina3'
        - 'https://github.com/Matthew-Spina'
google_site_verification: google_meta_tag_verification
baseurl: ""
timezone: Asia/Shanghai
google_analytics:
    id: ""
    pv:
        enabled: false
        proxy_url: ""
        proxy_endpoint: ""
        cache: false
disqus:
    comments: false
    shortname: ""
theme_mode: dual
toc: true
paginate: 10
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        css_class: highlight
        span:
            line_numbers: false
        block:
            line_numbers: true
            start_line: 1
permalink: '/posts/:title/'
defaults:
    -
        scope:
            path: ""
            type: posts
        values:
            layout: post
            comments: true
            toc: true
            location: Post
            breadcrumb: [{label: Posts, url: /}]
    -
        scope:
            path: _drafts
        values:
            comments: true
    -
        scope:
            path: tags
        values:
            tab_active: Tags
            location: Tag
            breadcrumb: [{label: Home, url: /}, {label: Tags, url: /tabs/tags/}]
    -
        scope:
            path: categories
        values:
            tab_active: Categories
            location: Category
            breadcrumb: [{label: Home, url: /}, {label: Categories, url: /tabs/categories/}]
    -
        scope:
            path: tabs
        values:
            layout: page
            dynamic_title: true
            breadcrumb: [{label: Home, url: /}]
    -
        scope:
            path: assets/data
        values:
            layout: compress
sass:
    sass_dir: /assets/css
    style: compressed
compress_html:
    clippings: all
    comments:
        - '<!-- '
        - ' -->'
    endings:
        - html
        - head
        - body
        - dt
        - dd
        - rt
        - rp
        - optgroup
        - option
        - colgroup
        - caption
        - thead
        - tbody
        - tfoot
        - tr
        - td
        - th
    profile: false
    blanklines: false
    ignore:
        envs: []
exclude:
    - vendor
    - Gemfile.lock
    - Gemfile
    - tools
    - docs
    - README.md
sitemap_exclude:
    fuzzy:
        - /assets/
    accurate:
        - /norobots/
        - /tabs/
        - /categories/
        - /tags/
        - /posts/
        - 404.html
        - feed.xml
        - sitemap.xml
        - robots.txt
        - redirects.json
